#port
server:
  port: 9090

#DataSource
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/to_do_list?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
      pool-name: HikariPool
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false #개발시 새로고침시 적용

---
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

#Mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

#spring.main.allow-circular-references=true
